# Generated by Django 4.2.3 on 2024-09-04 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_post', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('content', models.TextField()),
                ('header_post', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL товара')),
            ],
        ),
        migrations.CreateModel(
            name='PostImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(upload_to='img/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postimg', to='upload.postmodel')),
            ],
        ),
    ]
